server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8082/auth/user